language: node_js
node_js:
  - "10"

# safelist
branches:
  only:
  - master

os:
  - linux
  - osx
dist: trusty

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get update;
      sudo apt-get install g++-multilib;
      sudo apt-get install -y build-essential;
      sudo apt-get install libudev-dev;
    fi
  - npm install -g vsce
  - npm install -g node-gyp
  - npm install -g gulp

install:
  - npm install

script:
  - gulp buildDll --repoUrl="https://github.com/tessel/node-usb" --token="f0217db0f5da9411d3d55c286da59eeb436fda5d" --tag="downloads"
