language: node_js
node_js:
  - "6.9"

os:
  - linux
  - osx

before_install:
  - sudo apt-get update
  - sudo apt-get install g++-multilib
  - npm install -g vsce
  - sudo npm install -g node-gyp
  - npm install -g gulp

install:
  - npm install

script:
  - gulp buildDll --repoUrl="$REPO_URL"

# safelist
branches:
  only:
  - master
