language: node_js
node_js:
  - "6.9"

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install g++-multilib
  - npm install -g vsce
  - npm install -g node_gyp
  - npm install -g gulp

install:
  - npm install

script:
  - gulp buildSerialPortLib

# safelist
branches:
  only:
  - master
