environment:
  nodejs_version: "6.10.2"

# safelist
branches:
  only:
    - master

install:
  - npm install -g node-gyp
  - npm install -g gulp
  - npm install

build_script:
  - gulp buildDll --repoUrl="https://github.com/Microsoft/vscode-arduino.git" --token="ca9b802c6ba94da8ac85605b70897521cdbfc189" --tag="downloads"
  