environment:
  nodejs_version: "6.10.2"

# safelist
branches:
  only:
    - master

install:
  - npm install -g node-gyp
  - npm install -g gulp
  - npm install

build_script:
  - gulp buildDll --repoUrl="https://github.com/Microsoft/vscode-arduino.git" --token="f0217db0f5da9411d3d55c286da59eeb436fda5d" --tag="downloads"
  