environment:
  nodejs_version: "6.10.2"

# safelist
branches:
  only:
    - master

install:
  - npm install -g node-gyp
  - npm install -g gulp
  - npm install

build_script:
  - gulp buildDll --repoUrl="https://github.com/tessel/node-usb" --token="https://github.com/BW-Song/serialport.node" --tag="downloads"
  