environment:
  nodejs_version: "6.10.2"

# safelist
branches:
  only:
    - master

install:
  - npm install -g node-gyp
  - npm install -g gulp
  - npm install

build_script:
  - gulp buildDll --repoUrl="%REPO_URL%" --token="%API_TOKEN%" --tag="downloads"
  